### ISSUE TITLE
Properties 

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#6]
I have been reviewing the work that I did previously, and when I went through properties again, I think I might've confused myself.

In Lab_08 Part 2,  line 46: I tried type make it so if someone entered "parrot" as a colour, the value to be returned is N/A. However, this does not work. 

Also Lab_08 Part 3: I wanted an ArgumentOutOfRangeException to be thrown in the set method if someone entered an incorrect integer, however it does not work. 

I'm not sure if I am misunderstanding properties, and incorrectly treating them like methods?

**Comment by philanderson888** [comment]
Fields are often PRIVATE and declared

private string _myField;

Properties are usually declared as non-private eg

public string MyProperty {get;set;}

**Comment by philanderson888** [comment]
So in 

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Lab_08_Part2_Classes_GetSet/Program.cs

lines 16-20 you should remove the {get; set;}

All of your other code looks good Nish.

However you have been 'tricked' by some 'dodgy syntax' and as always - the devil is in the fine detail !  It's pretty much perfect bar just one small tiny error, so you're doing good!

Rather than tell you the answer straight away can you please turn on a 'debugger' by setting a break point in your program.  Then analyse in detail what is happening in lines 110 and 111 until you work out what is going wrong.

Message me tomorrow if you can't work it out yourself.  But it should be easy and you will kick yourself if you just turn on a debugger and press F11 to step into the detail of the code line by line and analyse what is happening.  You can also hover over variables to see their value in debug mode which is also very helpful, and using the Autos window can save time too (Debug=> Windows=> Auto when running in Debug mode)

Happy Debugging 

Phil

**Comment by nishman89** [comment]
Thanks Phil, just got in now, so will review it! Will update it ASAP and let you know what I found :)

**Comment by nishman89** [comment]
Done!!! A few questions - do I always have to declare the property like I did in the code? And I think my idea of fields and properties have changed - why can't a method be used to edit change an objects field instead of a property. Does that make sense?

**Comment by philanderson888** [comment]
Yes I think you have fixed it at line

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Lab_08_Part2_Classes_GetSet/Program.cs

Line 83

When you call line 83 it invokes the 'set' code and hence 'N/A' is put into the variable content.

Well done!

## Fields, Properties and Methods!

Fields
private string _privateField;       

Properties
public string MyProperty {get;set;}   // autoimplemented properties.  These DON'T NEED A METHOD TO ACCESS.

Constructor Method is used to set INITIAL VALUES
public MyClass(string privateField){  this._privateField = privateField }

Methods can be used to ACCESS PRIVATE FIELDS IF NECESSARY
public getPrivateField(){
  get {  return this._privateField; }
  set {  this._privateField = value; }
}

**Comment by nishman89** [comment]
Amazing, sorry for the late reply! I've worked on the interface bonus lab. I'm also practising more on interfaces - sorting objects.

**Comment by philanderson888** [comment]
No problem; keep me updated!

**Comment by nishman89** [comment]
Done
